require_relative 'test_center_utils'

action_examples, _, action_integration_tests = action_info
action_examples.each do |action_name, examples|
  examples.each_with_index do |example, index|
    lane_name = "example_#{action_name}_#{index}"
    lane lane_name.to_sym do
      # rubocop:disable Security/Eval
      eval(example)
      # rubocop:enable Security/Eval
    end
  end
end

action_integration_tests.each do |action_name, integration_tests|
  integration_tests.each_with_index do |integration_test, index|
    lane_name = "integration_test_#{action_name}_#{index}"
    lane lane_name.to_sym do
      # rubocop:disable Security/Eval
      eval(integration_test)
      # rubocop:enable Security/Eval
    end
  end
end

lane :issue_283 do
  multi_scan(
    workspace: File.absolute_path('../AtomicBoy/AtomicBoy.xcworkspace'),
    scheme: 'AtomicBoy',
    try_count: 3,
    output_types: 'json',
    output_files: 'report.json',
    fail_build: false
  )
  xcov(
    workspace: File.absolute_path('../AtomicBoy/AtomicBoy.xcworkspace'),
    scheme: 'AtomicBoy',
    json_report: true,
    markdown_report: true
  )
end